version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14  # Optional, only if you need a specific runtime like Node.js
    commands:
      - echo "Preparing environment..."
  build:
    commands:
      - echo "Fetching files from GitHub..."
      - git clone https://github.com/ultrasur/simple-dynamic-site.git
      - cd simple-dynamic-site
      - echo "Files fetched from GitHub."
      - echo "Running build steps... (if any)"
      # Any additional build commands can go here (e.g., minification, bundling, etc.)
      - echo "Build complete."

artifacts:
  files:
    - simple-dynamic-site/index.html
    - simple-dynamic-site/styles.css
    - simple-dynamic-site/script.js
