version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14  # Optional if you're using Node.js or need any specific runtime
    commands:
      - echo "Installing dependencies..."
  build:
    commands:
      - echo "Starting build..."
      # You can add build commands here if needed (e.g., minification, etc.)
      - echo "Build completed."
  post_build:
    commands:
      - echo "Copying files to S3 bucket..."
      - aws s3 cp index.html s3://your-s3-bucket-name/
      - aws s3 cp styles.css s3://your-s3-bucket-name/
      - aws s3 cp script.js s3://your-s3-bucket-name/

artifacts:
  files:
    - index.html
    - styles.css
    - script.js